- hosts: all
  user: vagrant
  tasks:
  - name: Find old source RPMs
    shell: ls /home/vagrant/xen*src.rpm
    register: rpms_to_clean
    ignore_errors: yes
  - name: Remove older source RPMs
    file: name={{item}} state=absent
    with_items: rpms_to_clean.stdout_lines
  - name: Clean out the build directories
    file: name=/home/vagrant/rpmbuild state=absent
  - name: Make the destination directory
    file: name=/vagrant/repos/{{ansible_distribution_version}} state=directory
  - name: Fetch Xen Source rpm
    raw: dnf download --source xen
  - name: Install Xen Source rpm
    shell: rpm -i "xen*src.rpm"
  - name: Install build dependencies.
    shell: dnf builddep -y /home/vagrant/rpmbuild/SPECS/xen.spec
    sudo: true
  - name: Copy xen.spec to halvm-xen.spec.
    shell: cp xen.spec halvm-xen.spec chdir=/home/vagrant/rpmbuild/SPECS
  - name: Replace %{name} with xen.
    replace: dest=/home/vagrant/rpmbuild/SPECS/halvm-xen.spec regexp="%{name}" replace='xen'
  - name: Fix the Name field.
    replace: dest=/home/vagrant/rpmbuild/SPECS/halvm-xen.spec regexp="^Name:.*xen$" replace="Name:halvm-xen"
  - name: Fix the URL field.
    replace: dest=/home/vagrant/rpmbuild/SPECS/halvm-xen.spec regexp="^URL:.*$" replace="URL:http://halvm.org/"
  - name: Fix the setup command.
    replace: dest=/home/vagrant/rpmbuild/SPECS/halvm-xen.spec regexp="^%setup -q" replace="%setup -q -n xen-%{version}"
  - name: Make sure to build Xen with verbose=y
    replace: dest=/home/vagrant/rpmbuild/SPECS/halvm-xen.spec regexp="dist-xen$" replace='verbose=y dist-xen'
  - name: Build the RPMs
    shell: rpmbuild -ba rpmbuild/SPECS/halvm-xen.spec
  - name: Copy the binary RPMs
    shell: cp -r rpmbuild/RPMS /vagrant/repos/{{ansible_distribution_version}}
  - name: Copy the source RPMs
    shell: cp -r rpmbuild/SRPMS /vagrant/repos/{{ansible_distribution_version}}

 
